# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29dd94fa35403fe57a45dc5ff7c102f78688d0335d551bf02b874e774cbe14d2028c2d8a8a6c12395007aa20dfee9395bbce82e1d001fd1a2f3e607f2d6b09e6

test:
  secret_key_base: 2ec7406ca6750756bd612a30cc5b928bbc8579fd16fd55165662e120630969061bfe5eb9400d21c47f6288fde75078cd97152462fa15972386bd22bf4401f449

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
